name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 El trabajo fue activado automáticamente por un evento ${{ github.event_name }}."
      - run: echo "🐧 Este trabajo ahora se está ejecutando en un servidor ${{ runner.os }} alojado por GitHub!"
      - run: echo "🔎 El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 El repositorio ${{ github.repository }} ha sido clonado al runner."
      - run: echo "🖥️ El flujo de trabajo ahora está listo para probar tu código en el runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 El estado de este trabajo es ${{ job.status }}."
